sudo: required
services:
  - docker

before_install:
  - docker build -t jvanryck/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jvanryck/react-test npm test -- --coverage

after_success:
  - docker build -t jvanryck/multi-client ./client
  - docker build -t jvanryck/multi-nginx ./nginx
  - docker build -t jvanryck/multi-worker ./worker
  - docker build -t jvanryck/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jvanryck/multi-client
  - docker push jvanryck/multi-nginx
  - docker push jvanryck/multi-worker
  - docker push jvanryck/multi-server